# Site settings
title: "Raumausstattung Frese"
email: "kontakt@raumausstattung-frese.de"
phone: +49 179 5376813
description: "Eduard Frese - Experte für Raumdesign in Koblenz. Über 15 Jahre Erfahrung in Maler-, Bodenbelags-, Wand-, Trockenbau- und Tapezierarbeiten."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.raumausstattung-frese.de" # the base hostname & protocol for your site


twitter_username:
github_username:

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
